# Generated by Django 4.1.4 on 2022-12-28 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_alter_comment_event_alter_seat_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchaser_email', models.EmailField(max_length=254)),
                ('purchaser_number', models.CharField(max_length=16)),
                ('cc_number', models.CharField(max_length=64)),
                ('cc_expiry', models.CharField(max_length=64)),
                ('cc_code', models.CharField(max_length=64)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('updated_time', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('CANCELLED', 'CANCELLED'), ('FAILED', 'FAILED')], max_length=64)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='events.event')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='events.seat')),
            ],
        ),
    ]
