# Generated by Django 4.1.4 on 2022-12-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
